### PR TITLE
Global css

### PR DESCRIPTION
**Pull request by alodahl**
###UPDATES:
- BEM compliant
- bring repeated variables into global.css
- import global css to files where variable are used
- global styles run in unstack/web

### CODE REVIEW

**Comment by heyellieday** [comment]
@alodahl, Is the plan to port this over to /web?

**Comment by alodahl** [comment]
Of course. I had nearly finished it before we discussed the css on Sunday, which is why it is in the gatsby folder. Should I bring it into a web/ folder before I merge?

**Comment by alodahl** [comment]
Alright @heyellieday , it's in unstack!

**Comment by alodahl** [comment]
@heyellieday, should we change the deploy preview to unstack/web now?  Lian and I are going to be working there starting today.

**Comment by alodahl** [comment]
can I merge it?

**Pull request merged**
